name: Build

on:
  workflow_dispatch:
  push:
    paths-ignore: [ '*.md', 'assets/**', 'LICENSE']
    branches: [ 'feature/**', "release/**", "bug/**", "issue/**" ]
  pull_request:
    paths-ignore: [ '*.md', 'assets/**', 'LICENSE' ]
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          architecture: x64

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run tests
        run: ./gradlew build test